FROM python:3.11-slim
ADD main.py .
ADD containerManager.py .
RUN pip install docker
RUN pip install flask
RUN pip install flask-cors
CMD ["python", "./main.py"] 

# BUILD DOCKER IMAGE
# docker build -t backend .

# RUN DOCKER IMAGE
# docker run -v /var/run/docker.sock:/var/run/docker.sock -p 4000:4000 backend:latest
