FROM python:3.11-slim
ADD main.py .
ADD containerManager.py .
RUN pip install docker
RUN pip install flask
CMD ["python", "./main.py"] 

# TO BUILD DOCKER IMAGE
# docker build -t backend .

# RUN DOCKER IMAGE WITH THE FOLLOWING AS VOLUME
# docker run -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 backend:latest
